// AUTH_TYPES
export const CLEAR_AUTH_ERROR = "CLEAR_AUTH_ERROR";
export const PROFILE_CHANGED = "PROFILE_CHANGED";
export const AUTHENTICATED = "AUTHENTICATED";
export const AUTH_LOADING = "AUTH_LOADING";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGOUT = "LOGOUT";

export const MAKE_PAYMENT = "MAKE_PAYMENT";
export const GET_ALL_TRANSACTIONS = "GET_ALL_TRANSACTIONS";
