// AUTH_TYPES
export const CLEAR_AUTH_ERROR = "CLEAR_AUTH_ERROR";
export const AUTHENTICATED = "AUTHENTICATED";
export const AUTH_LOADING = "AUTH_LOADING";
export const AUTH_ERROR = "AUTH_ERROR";
export const PROFILE_ERROR = "PROFILE_ERROR";
export const LOGOUT = "LOGOUT";
export const COURSE_ERROR = "COURSE_ERROR";
export const CLEAR_COURSE_POPUP = "CLEAR_COURSE_POPUP";
export const GET_CONTENTS = "GET_CONTENTS";
export const AUTH_STATUS = "AUTH_STATUS";
export const PROFILE_CHANGED = "PROFILE_CHANGED";
export const USER_LOADED = "USER_LOADED";

